spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

external:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    base-url: ${NAVER_BASE_URL}

  api-football:
    api-key: ${API_FOOTBALL_KEY}
    api-base-uri: ${API_BASE_URI}

retry:
  team-statistics:
    max-attempts: ${RETRY_TEAM_STATISTICS_MAX_ATTEMPTS:3}
    delay: ${RETRY_TEAM_STATISTICS_DELAY:1000}
  player:
    max-attempts: ${RETRY_PLAYER_MAX_ATTEMPTS:3}
    delay: ${RETRY_PLAYER_DELAY:1000}
  match:
    max-attempts: ${RETRY_MATCH_MAX_ATTEMPTS:3}
    delay: ${RETRY_MATCH_DELAY:1000}

cloudflare:
  r2:
    endpoint: https://c617d97cfcb06429e7af174bfa03ba9b.r2.cloudflarestorage.com
    public-url: https://pub-8dfe7ca8163c400aac6a83640c67edb4.r2.dev
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket: manuhub
