package backend.manuhub.rank;

import backend.manuhub.annotation.CommonErrorResponses;
import backend.manuhub.rank.dto.PlayerRankGetResponse;
import backend.manuhub.rank.dto.TeamRankGetResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;

@Tag(name = "순위 관련 API")
public interface RankAPI {

    @Operation(
            summary = "순위 관련 조회 API",
            description = "프리미어리그의 순위를 목록으로 조회합니다.",
            responses = {
                    @ApiResponse(
                            responseCode = "200", description = "순위 조회 성공",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = TeamRankGetResponse.class),
                                    examples = @ExampleObject(value = """
                                            {
                                                "season": "2025-26",
                                                "ranks": [
                                                    {
                                                        "rank": 1,
                                                        "teamId": 42,
                                                        "teamName": "Arsenal",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/42.png",
                                                        "points": 85,
                                                        "played": 38,
                                                        "win": 26,
                                                        "draw": 7,
                                                        "lose": 5,
                                                        "goalsFor": 71,
                                                        "goalsAgainst": 27,
                                                        "goalsDiff": 44,
                                                        "form": "WWWWW"
                                                    },
                                                    {
                                                        "rank": 2,
                                                        "teamId": 50,
                                                        "teamName": "Manchester City",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/50.png",
                                                        "points": 78,
                                                        "played": 38,
                                                        "win": 23,
                                                        "draw": 9,
                                                        "lose": 6,
                                                        "goalsFor": 77,
                                                        "goalsAgainst": 35,
                                                        "goalsDiff": 42,
                                                        "form": "LDWWD"
                                                    },
                                                    {
                                                        "rank": 3,
                                                        "teamId": 33,
                                                        "teamName": "Manchester United",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/33.png",
                                                        "points": 71,
                                                        "played": 38,
                                                        "win": 20,
                                                        "draw": 11,
                                                        "lose": 7,
                                                        "goalsFor": 69,
                                                        "goalsAgainst": 50,
                                                        "goalsDiff": 19,
                                                        "form": "WWDWW"
                                                    },
                                                    {
                                                        "rank": 4,
                                                        "teamId": 66,
                                                        "teamName": "Aston Villa",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/66.png",
                                                        "points": 65,
                                                        "played": 38,
                                                        "win": 19,
                                                        "draw": 8,
                                                        "lose": 11,
                                                        "goalsFor": 56,
                                                        "goalsAgainst": 49,
                                                        "goalsDiff": 7,
                                                        "form": "WWDLL"
                                                    },
                                                    {
                                                        "rank": 5,
                                                        "teamId": 40,
                                                        "teamName": "Liverpool",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/40.png",
                                                        "points": 60,
                                                        "played": 38,
                                                        "win": 17,
                                                        "draw": 9,
                                                        "lose": 12,
                                                        "goalsFor": 63,
                                                        "goalsAgainst": 53,
                                                        "goalsDiff": 10,
                                                        "form": "DLDLW"
                                                    },
                                                    {
                                                        "rank": 6,
                                                        "teamId": 35,
                                                        "teamName": "Bournemouth",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/35.png",
                                                        "points": 57,
                                                        "played": 38,
                                                        "win": 13,
                                                        "draw": 18,
                                                        "lose": 7,
                                                        "goalsFor": 58,
                                                        "goalsAgainst": 54,
                                                        "goalsDiff": 4,
                                                        "form": "DDWWD"
                                                    },
                                                    {
                                                        "rank": 7,
                                                        "teamId": 746,
                                                        "teamName": "Sunderland",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/746.png",
                                                        "points": 54,
                                                        "played": 38,
                                                        "win": 14,
                                                        "draw": 12,
                                                        "lose": 12,
                                                        "goalsFor": 42,
                                                        "goalsAgainst": 48,
                                                        "goalsDiff": -6,
                                                        "form": "WWDDL"
                                                    },
                                                    {
                                                        "rank": 8,
                                                        "teamId": 51,
                                                        "teamName": "Brighton",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/51.png",
                                                        "points": 53,
                                                        "played": 38,
                                                        "win": 14,
                                                        "draw": 11,
                                                        "lose": 13,
                                                        "goalsFor": 52,
                                                        "goalsAgainst": 46,
                                                        "goalsDiff": 6,
                                                        "form": "LLWLW"
                                                    },
                                                    {
                                                        "rank": 9,
                                                        "teamId": 55,
                                                        "teamName": "Brentford",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/55.png",
                                                        "points": 53,
                                                        "played": 38,
                                                        "win": 14,
                                                        "draw": 11,
                                                        "lose": 13,
                                                        "goalsFor": 55,
                                                        "goalsAgainst": 52,
                                                        "goalsDiff": 3,
                                                        "form": "DDLWL"
                                                    },
                                                    {
                                                        "rank": 10,
                                                        "teamId": 49,
                                                        "teamName": "Chelsea",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/49.png",
                                                        "points": 52,
                                                        "played": 38,
                                                        "win": 14,
                                                        "draw": 10,
                                                        "lose": 14,
                                                        "goalsFor": 58,
                                                        "goalsAgainst": 52,
                                                        "goalsDiff": 6,
                                                        "form": "LWDLL"
                                                    },
                                                    {
                                                        "rank": 11,
                                                        "teamId": 36,
                                                        "teamName": "Fulham",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/36.png",
                                                        "points": 52,
                                                        "played": 38,
                                                        "win": 15,
                                                        "draw": 7,
                                                        "lose": 16,
                                                        "goalsFor": 47,
                                                        "goalsAgainst": 51,
                                                        "goalsDiff": -4,
                                                        "form": "WDLLW"
                                                    },
                                                    {
                                                        "rank": 12,
                                                        "teamId": 34,
                                                        "teamName": "Newcastle",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/34.png",
                                                        "points": 49,
                                                        "played": 38,
                                                        "win": 14,
                                                        "draw": 7,
                                                        "lose": 17,
                                                        "goalsFor": 53,
                                                        "goalsAgainst": 55,
                                                        "goalsDiff": -2,
                                                        "form": "LWDWL"
                                                    },
                                                    {
                                                        "rank": 13,
                                                        "teamId": 45,
                                                        "teamName": "Everton",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/45.png",
                                                        "points": 49,
                                                        "played": 38,
                                                        "win": 13,
                                                        "draw": 10,
                                                        "lose": 15,
                                                        "goalsFor": 47,
                                                        "goalsAgainst": 50,
                                                        "goalsDiff": -3,
                                                        "form": "LLDDL"
                                                    },
                                                    {
                                                        "rank": 14,
                                                        "teamId": 63,
                                                        "teamName": "Leeds",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/63.png",
                                                        "points": 47,
                                                        "played": 38,
                                                        "win": 11,
                                                        "draw": 14,
                                                        "lose": 13,
                                                        "goalsFor": 49,
                                                        "goalsAgainst": 56,
                                                        "goalsDiff": -7,
                                                        "form": "LWDWD"
                                                    },
                                                    {
                                                        "rank": 15,
                                                        "teamId": 52,
                                                        "teamName": "Crystal Palace",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/52.png",
                                                        "points": 45,
                                                        "played": 38,
                                                        "win": 11,
                                                        "draw": 12,
                                                        "lose": 15,
                                                        "goalsFor": 41,
                                                        "goalsAgainst": 51,
                                                        "goalsDiff": -10,
                                                        "form": "LDLDL"
                                                    },
                                                    {
                                                        "rank": 16,
                                                        "teamId": 65,
                                                        "teamName": "Nottingham Forest",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/65.png",
                                                        "points": 44,
                                                        "played": 38,
                                                        "win": 11,
                                                        "draw": 11,
                                                        "lose": 16,
                                                        "goalsFor": 48,
                                                        "goalsAgainst": 51,
                                                        "goalsDiff": -3,
                                                        "form": "DLDWW"
                                                    },
                                                    {
                                                        "rank": 17,
                                                        "teamId": 47,
                                                        "teamName": "Tottenham",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/47.png",
                                                        "points": 41,
                                                        "played": 38,
                                                        "win": 10,
                                                        "draw": 11,
                                                        "lose": 17,
                                                        "goalsFor": 48,
                                                        "goalsAgainst": 57,
                                                        "goalsDiff": -9,
                                                        "form": "WLDWW"
                                                    },
                                                    {
                                                        "rank": 18,
                                                        "teamId": 48,
                                                        "teamName": "West Ham",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/48.png",
                                                        "points": 39,
                                                        "played": 38,
                                                        "win": 10,
                                                        "draw": 9,
                                                        "lose": 19,
                                                        "goalsFor": 46,
                                                        "goalsAgainst": 65,
                                                        "goalsDiff": -19,
                                                        "form": "WLLLW"
                                                    },
                                                    {
                                                        "rank": 19,
                                                        "teamId": 44,
                                                        "teamName": "Burnley",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/44.png",
                                                        "points": 22,
                                                        "played": 38,
                                                        "win": 4,
                                                        "draw": 10,
                                                        "lose": 24,
                                                        "goalsFor": 38,
                                                        "goalsAgainst": 75,
                                                        "goalsDiff": -37,
                                                        "form": "DLDLL"
                                                    },
                                                    {
                                                        "rank": 20,
                                                        "teamId": 39,
                                                        "teamName": "Wolves",
                                                        "teamLogo": "https://media.api-sports.io/football/teams/39.png",
                                                        "points": 20,
                                                        "played": 38,
                                                        "win": 3,
                                                        "draw": 11,
                                                        "lose": 24,
                                                        "goalsFor": 27,
                                                        "goalsAgainst": 68,
                                                        "goalsDiff": -41,
                                                        "form": "DDLDL"
                                                    }
                                                ]
                                            }
                                            """)
                            )
                    )
            }
    )
    @CommonErrorResponses
    public ResponseEntity<TeamRankGetResponse> getPLRank();

    @Operation(
            summary = "득점 순위 조회 API",
            description = "프리미어리그 득점 순위를 조회합니다. 시즌 시작 전에는 빈 리스트를 반환합니다.",
            responses = {
                    @ApiResponse(
                            responseCode = "200", description = "득점 순위 조회 성공",
                            content = @Content(
                                    mediaType = "application/json",
                                    examples = @ExampleObject(value = """
                                            {
                                                 "season": "2025-26",
                                                 "ranks": [
                                                     {
                                                         "rank": 1,
                                                         "playerId": 1100,
                                                         "playerName": "E. Haaland",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1100.png",
                                                         "teamId": 50,
                                                         "teamName": "Manchester City",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/50.png",
                                                         "goals": 27,
                                                         "assists": 8,
                                                         "appearences": 35,
                                                         "minutes": 2958,
                                                         "shots": 102,
                                                         "shotsOnTarget": 59,
                                                         "keyPasses": 25
                                                     },
                                                     {
                                                         "rank": 2,
                                                         "playerId": 196156,
                                                         "playerName": "Thiago",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/196156.png",
                                                         "teamId": 55,
                                                         "teamName": "Brentford",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/55.png",
                                                         "goals": 22,
                                                         "assists": 1,
                                                         "appearences": 38,
                                                         "minutes": 3295,
                                                         "shots": 67,
                                                         "shotsOnTarget": 43,
                                                         "keyPasses": 24
                                                     },
                                                     {
                                                         "rank": 3,
                                                         "playerId": 19366,
                                                         "playerName": "O. Watkins",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19366.png",
                                                         "teamId": 66,
                                                         "teamName": "Aston Villa",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/66.png",
                                                         "goals": 16,
                                                         "assists": 3,
                                                         "appearences": 37,
                                                         "minutes": 2864,
                                                         "shots": 60,
                                                         "shotsOnTarget": 38,
                                                         "keyPasses": 23
                                                     },
                                                     {
                                                         "rank": 4,
                                                         "playerId": 10329,
                                                         "playerName": "João Pedro",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/10329.png",
                                                         "teamId": 49,
                                                         "teamName": "Chelsea",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/49.png",
                                                         "goals": 15,
                                                         "assists": 5,
                                                         "appearences": 35,
                                                         "minutes": 2687,
                                                         "shots": 52,
                                                         "shotsOnTarget": 28,
                                                         "keyPasses": 29
                                                     },
                                                     {
                                                         "rank": 4,
                                                         "playerId": 18746,
                                                         "playerName": "M. Gibbs-White",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/18746.png",
                                                         "teamId": 65,
                                                         "teamName": "Nottingham Forest",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/65.png",
                                                         "goals": 15,
                                                         "assists": 4,
                                                         "appearences": 37,
                                                         "minutes": 3110,
                                                         "shots": 59,
                                                         "shotsOnTarget": 32,
                                                         "keyPasses": 49
                                                     },
                                                     {
                                                         "rank": 6,
                                                         "playerId": 18979,
                                                         "playerName": "V. Gyökeres",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/18979.png",
                                                         "teamId": 42,
                                                         "teamName": "Arsenal",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/42.png",
                                                         "goals": 14,
                                                         "assists": 1,
                                                         "appearences": 36,
                                                         "minutes": 2254,
                                                         "shots": 41,
                                                         "shotsOnTarget": 22,
                                                         "keyPasses": 20
                                                     },
                                                     {
                                                         "rank": 6,
                                                         "playerId": 18766,
                                                         "playerName": "D. Calvert-Lewin",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/18766.png",
                                                         "teamId": 63,
                                                         "teamName": "Leeds",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/63.png",
                                                         "goals": 14,
                                                         "assists": 1,
                                                         "appearences": 35,
                                                         "minutes": 2726,
                                                         "shots": 66,
                                                         "shotsOnTarget": 34,
                                                         "keyPasses": 20
                                                     },
                                                     {
                                                         "rank": 8,
                                                         "playerId": 1469,
                                                         "playerName": "D. Welbeck",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1469.png",
                                                         "teamId": 51,
                                                         "teamName": "Brighton",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/51.png",
                                                         "goals": 13,
                                                         "assists": 1,
                                                         "appearences": 37,
                                                         "minutes": 2268,
                                                         "shots": 46,
                                                         "shotsOnTarget": 28,
                                                         "keyPasses": 20
                                                     },
                                                     {
                                                         "rank": 8,
                                                         "playerId": 368030,
                                                         "playerName": "E. Kroupi",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/368030.png",
                                                         "teamId": 35,
                                                         "teamName": "Bournemouth",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/35.png",
                                                         "goals": 13,
                                                         "assists": 0,
                                                         "appearences": 33,
                                                         "minutes": 1690,
                                                         "shots": 33,
                                                         "shotsOnTarget": 22,
                                                         "keyPasses": 22
                                                     },
                                                     {
                                                         "rank": 10,
                                                         "playerId": 25927,
                                                         "playerName": "J. Mateta",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/25927.png",
                                                         "teamId": 52,
                                                         "teamName": "Crystal Palace",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/52.png",
                                                         "goals": 12,
                                                         "assists": 0,
                                                         "appearences": 32,
                                                         "minutes": 2222,
                                                         "shots": 56,
                                                         "shotsOnTarget": 32,
                                                         "keyPasses": 9
                                                     },
                                                     {
                                                         "rank": 11,
                                                         "playerId": 2413,
                                                         "playerName": "Richarlison",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/2413.png",
                                                         "teamId": 47,
                                                         "teamName": "Tottenham",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/47.png",
                                                         "goals": 11,
                                                         "assists": 4,
                                                         "appearences": 32,
                                                         "minutes": 1957,
                                                         "shots": 47,
                                                         "shotsOnTarget": 26,
                                                         "keyPasses": 20
                                                     },
                                                     {
                                                         "rank": 11,
                                                         "playerId": 174565,
                                                         "playerName": "H. Ekitike",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/174565.png",
                                                         "teamId": 40,
                                                         "teamName": "Liverpool",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/40.png",
                                                         "goals": 11,
                                                         "assists": 4,
                                                         "appearences": 28,
                                                         "minutes": 1810,
                                                         "shots": 48,
                                                         "shotsOnTarget": 19,
                                                         "keyPasses": 21
                                                     },
                                                     {
                                                         "rank": 11,
                                                         "playerId": 20589,
                                                         "playerName": "B. Mbeumo",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/20589.png",
                                                         "teamId": 33,
                                                         "teamName": "Manchester United",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/33.png",
                                                         "goals": 11,
                                                         "assists": 3,
                                                         "appearences": 33,
                                                         "minutes": 2621,
                                                         "shots": 59,
                                                         "shotsOnTarget": 32,
                                                         "keyPasses": 47
                                                     },
                                                     {
                                                         "rank": 11,
                                                         "playerId": 115589,
                                                         "playerName": "B. Šeško",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/115589.png",
                                                         "teamId": 33,
                                                         "teamName": "Manchester United",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/33.png",
                                                         "goals": 11,
                                                         "assists": 1,
                                                         "appearences": 30,
                                                         "minutes": 1636,
                                                         "shots": 51,
                                                         "shotsOnTarget": 34,
                                                         "keyPasses": 9
                                                     },
                                                     {
                                                         "rank": 11,
                                                         "playerId": 36927,
                                                         "playerName": "Z. Flemming",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/36927.png",
                                                         "teamId": 44,
                                                         "teamName": "Burnley",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/44.png",
                                                         "goals": 11,
                                                         "assists": 0,
                                                         "appearences": 29,
                                                         "minutes": 1807,
                                                         "shots": 38,
                                                         "shotsOnTarget": 21,
                                                         "keyPasses": 10
                                                     },
                                                     {
                                                         "rank": 16,
                                                         "playerId": 19221,
                                                         "playerName": "H. Wilson",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19221.png",
                                                         "teamId": 36,
                                                         "teamName": "Fulham",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/36.png",
                                                         "goals": 10,
                                                         "assists": 7,
                                                         "appearences": 36,
                                                         "minutes": 2701,
                                                         "shots": 51,
                                                         "shotsOnTarget": 25,
                                                         "keyPasses": 39
                                                     },
                                                     {
                                                         "rank": 16,
                                                         "playerId": 19170,
                                                         "playerName": "M. Rogers",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19170.png",
                                                         "teamId": 66,
                                                         "teamName": "Aston Villa",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/66.png",
                                                         "goals": 10,
                                                         "assists": 6,
                                                         "appearences": 37,
                                                         "minutes": 3285,
                                                         "shots": 58,
                                                         "shotsOnTarget": 32,
                                                         "keyPasses": 47
                                                     },
                                                     {
                                                         "rank": 16,
                                                         "playerId": 1165,
                                                         "playerName": "Matheus Cunha",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1165.png",
                                                         "teamId": 33,
                                                         "teamName": "Manchester United",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/33.png",
                                                         "goals": 10,
                                                         "assists": 2,
                                                         "appearences": 33,
                                                         "minutes": 2503,
                                                         "shots": 58,
                                                         "shotsOnTarget": 35,
                                                         "keyPasses": 35
                                                     },
                                                     {
                                                         "rank": 16,
                                                         "playerId": 19281,
                                                         "playerName": "A. Semenyo",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19281.png",
                                                         "teamId": 35,
                                                         "teamName": "Bournemouth",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/35.png",
                                                         "goals": 10,
                                                         "assists": 3,
                                                         "appearences": 20,
                                                         "minutes": 1798,
                                                         "shots": 42,
                                                         "shotsOnTarget": 27,
                                                         "keyPasses": 25
                                                     },
                                                     {
                                                         "rank": 16,
                                                         "playerId": 5996,
                                                         "playerName": "E. Fernández",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/5996.png",
                                                         "teamId": 49,
                                                         "teamName": "Chelsea",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/49.png",
                                                         "goals": 10,
                                                         "assists": 4,
                                                         "appearences": 36,
                                                         "minutes": 3134,
                                                         "shots": 52,
                                                         "shotsOnTarget": 31,
                                                         "keyPasses": 69
                                                     }
                                                 ]
                                             }
                                        """)))})
    @CommonErrorResponses
    ResponseEntity<PlayerRankGetResponse> getPLTopScorers();

    @Operation(
            summary = "어시스트 순위 조회 API",
            description = "프리미어리그 어시스트 순위를 조회합니다. 시즌 시작 전에는 빈 리스트를 반환합니다.",
            responses = {
                    @ApiResponse(
                            responseCode = "200", description = "어시스트 순위 조회 성공",
                            content = @Content(
                                    mediaType = "application/json",
                                    examples = @ExampleObject(value = """
                                            {
                                                 "season": "2025-26",
                                                 "ranks": [
                                                     {
                                                         "rank": 1,
                                                         "playerId": 1485,
                                                         "playerName": "Bruno Fernandes",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1485.png",
                                                         "teamId": 33,
                                                         "teamName": "Manchester United",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/33.png",
                                                         "goals": 9,
                                                         "assists": 21,
                                                         "appearences": 35,
                                                         "minutes": 3066,
                                                         "shots": 55,
                                                         "shotsOnTarget": 24,
                                                         "keyPasses": 137
                                                     },
                                                     {
                                                         "rank": 2,
                                                         "playerId": 156477,
                                                         "playerName": "R. Cherki",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/156477.png",
                                                         "teamId": 50,
                                                         "teamName": "Manchester City",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/50.png",
                                                         "goals": 4,
                                                         "assists": 12,
                                                         "appearences": 33,
                                                         "minutes": 1806,
                                                         "shots": 32,
                                                         "shotsOnTarget": 13,
                                                         "keyPasses": 61
                                                     },
                                                     {
                                                         "rank": 3,
                                                         "playerId": 19428,
                                                         "playerName": "J. Bowen",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19428.png",
                                                         "teamId": 48,
                                                         "teamName": "West Ham",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/48.png",
                                                         "goals": 9,
                                                         "assists": 11,
                                                         "appearences": 38,
                                                         "minutes": 3410,
                                                         "shots": 50,
                                                         "shotsOnTarget": 28,
                                                         "keyPasses": 45
                                                     },
                                                     {
                                                         "rank": 4,
                                                         "playerId": 1100,
                                                         "playerName": "E. Haaland",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1100.png",
                                                         "teamId": 50,
                                                         "teamName": "Manchester City",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/50.png",
                                                         "goals": 27,
                                                         "assists": 8,
                                                         "appearences": 35,
                                                         "minutes": 2958,
                                                         "shots": 102,
                                                         "shotsOnTarget": 59,
                                                         "keyPasses": 25
                                                     },
                                                     {
                                                         "rank": 5,
                                                         "playerId": 19221,
                                                         "playerName": "H. Wilson",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19221.png",
                                                         "teamId": 36,
                                                         "teamName": "Fulham",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/36.png",
                                                         "goals": 10,
                                                         "assists": 7,
                                                         "appearences": 36,
                                                         "minutes": 2701,
                                                         "shots": 51,
                                                         "shotsOnTarget": 25,
                                                         "keyPasses": 39
                                                     },
                                                     {
                                                         "rank": 5,
                                                         "playerId": 306,
                                                         "playerName": "Mohamed Salah",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/306.png",
                                                         "teamId": 40,
                                                         "teamName": "Liverpool",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/40.png",
                                                         "goals": 7,
                                                         "assists": 7,
                                                         "appearences": 27,
                                                         "minutes": 2148,
                                                         "shots": 45,
                                                         "shotsOnTarget": 19,
                                                         "keyPasses": 49
                                                     },
                                                     {
                                                         "rank": 5,
                                                         "playerId": 1096,
                                                         "playerName": "D. Szoboszlai",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1096.png",
                                                         "teamId": 40,
                                                         "teamName": "Liverpool",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/40.png",
                                                         "goals": 6,
                                                         "assists": 7,
                                                         "appearences": 36,
                                                         "minutes": 3244,
                                                         "shots": 47,
                                                         "shotsOnTarget": 23,
                                                         "keyPasses": 78
                                                     },
                                                     {
                                                         "rank": 5,
                                                         "playerId": 895,
                                                         "playerName": "J. Garner",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/895.png",
                                                         "teamId": 45,
                                                         "teamName": "Everton",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/45.png",
                                                         "goals": 2,
                                                         "assists": 7,
                                                         "appearences": 38,
                                                         "minutes": 3426,
                                                         "shots": 34,
                                                         "shotsOnTarget": 14,
                                                         "keyPasses": 56
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 19170,
                                                         "playerName": "M. Rogers",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19170.png",
                                                         "teamId": 66,
                                                         "teamName": "Aston Villa",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/66.png",
                                                         "goals": 10,
                                                         "assists": 6,
                                                         "appearences": 37,
                                                         "minutes": 3285,
                                                         "shots": 58,
                                                         "shotsOnTarget": 32,
                                                         "keyPasses": 47
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 1946,
                                                         "playerName": "L. Trossard",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1946.png",
                                                         "teamId": 42,
                                                         "teamName": "Arsenal",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/42.png",
                                                         "goals": 6,
                                                         "assists": 6,
                                                         "appearences": 31,
                                                         "minutes": 2006,
                                                         "shots": 35,
                                                         "shotsOnTarget": 15,
                                                         "keyPasses": 36
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 1864,
                                                         "playerName": "Pedro Neto",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1864.png",
                                                         "teamId": 49,
                                                         "teamName": "Chelsea",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/49.png",
                                                         "goals": 5,
                                                         "assists": 6,
                                                         "appearences": 34,
                                                         "minutes": 2643,
                                                         "shots": 24,
                                                         "shotsOnTarget": 13,
                                                         "keyPasses": 55
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 20638,
                                                         "playerName": "E. Le Fée",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/20638.png",
                                                         "teamId": 746,
                                                         "teamName": "Sunderland",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/746.png",
                                                         "goals": 5,
                                                         "assists": 6,
                                                         "appearences": 36,
                                                         "minutes": 2953,
                                                         "shots": 24,
                                                         "shotsOnTarget": 12,
                                                         "keyPasses": 53
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 19187,
                                                         "playerName": "J. Grealish",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/19187.png",
                                                         "teamId": 45,
                                                         "teamName": "Everton",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/45.png",
                                                         "goals": 2,
                                                         "assists": 6,
                                                         "appearences": 20,
                                                         "minutes": 1631,
                                                         "shots": 14,
                                                         "shotsOnTarget": 8,
                                                         "keyPasses": 40
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 1464,
                                                         "playerName": "G. Xhaka",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/1464.png",
                                                         "teamId": 746,
                                                         "teamName": "Sunderland",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/746.png",
                                                         "goals": 1,
                                                         "assists": 6,
                                                         "appearences": 34,
                                                         "minutes": 2916,
                                                         "shots": 15,
                                                         "shotsOnTarget": 5,
                                                         "keyPasses": 34
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 37127,
                                                         "playerName": "M. Ødegaard",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/37127.png",
                                                         "teamId": 42,
                                                         "teamName": "Arsenal",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/42.png",
                                                         "goals": 1,
                                                         "assists": 6,
                                                         "appearences": 24,
                                                         "minutes": 1370,
                                                         "shots": 17,
                                                         "shotsOnTarget": 8,
                                                         "keyPasses": 40
                                                     },
                                                     {
                                                         "rank": 9,
                                                         "playerId": 2724,
                                                         "playerName": "L. Digne",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/2724.png",
                                                         "teamId": 66,
                                                         "teamName": "Aston Villa",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/66.png",
                                                         "goals": 0,
                                                         "assists": 6,
                                                         "appearences": 31,
                                                         "minutes": 1866,
                                                         "shots": 8,
                                                         "shotsOnTarget": 5,
                                                         "keyPasses": 26
                                                     },
                                                     {
                                                         "rank": 17,
                                                         "playerId": 10329,
                                                         "playerName": "João Pedro",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/10329.png",
                                                         "teamId": 49,
                                                         "teamName": "Chelsea",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/49.png",
                                                         "goals": 15,
                                                         "assists": 5,
                                                         "appearences": 35,
                                                         "minutes": 2687,
                                                         "shots": 52,
                                                         "shotsOnTarget": 28,
                                                         "keyPasses": 29
                                                     },
                                                     {
                                                         "rank": 17,
                                                         "playerId": 10135,
                                                         "playerName": "Bruno Guimarães",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/10135.png",
                                                         "teamId": 34,
                                                         "teamName": "Newcastle",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/34.png",
                                                         "goals": 9,
                                                         "assists": 5,
                                                         "appearences": 29,
                                                         "minutes": 2455,
                                                         "shots": 36,
                                                         "shotsOnTarget": 23,
                                                         "keyPasses": 46
                                                     },
                                                     {
                                                         "rank": 17,
                                                         "playerId": 247,
                                                         "playerName": "C. Gakpo",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/247.png",
                                                         "teamId": 40,
                                                         "teamName": "Liverpool",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/40.png",
                                                         "goals": 7,
                                                         "assists": 5,
                                                         "appearences": 36,
                                                         "minutes": 2765,
                                                         "shots": 54,
                                                         "shotsOnTarget": 21,
                                                         "keyPasses": 53
                                                     },
                                                     {
                                                         "rank": 17,
                                                         "playerId": 631,
                                                         "playerName": "P. Foden",
                                                         "playerPhoto": "https://media.api-sports.io/football/players/631.png",
                                                         "teamId": 50,
                                                         "teamName": "Manchester City",
                                                         "teamLogo": "https://media.api-sports.io/football/teams/50.png",
                                                         "goals": 7,
                                                         "assists": 5,
                                                         "appearences": 33,
                                                         "minutes": 2119,
                                                         "shots": 36,
                                                         "shotsOnTarget": 19,
                                                         "keyPasses": 56
                                                     }
                                                 ]
                                             }
                                        """)))})
    @CommonErrorResponses
    ResponseEntity<PlayerRankGetResponse> getPLTopAssists();
}
